name: Server CI/CD

on: [push]

env:
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Write Secrets
        run: |
          touch ./serviceAccountKey.json
          echo "$SERVICE_ACCOUNT_KEY" >> ./serviceAccountKey.json
          cat ./serviceAccountKey.json
        shell: bash
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name:  Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SERVICE_ACCOUNT_KEY
          path: ./serviceAccountKey.json
      - name: Build Maven
        run: |
          pwd
          cd Server
          mvn -B clean verify
      - name: Package Maven
        run: |
          ls
          pwd
          cd Server
          mvn -B package
      - name: Build Springboot image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: backend/app:latest
      - name: Change directory to frontend
        run: |
          cd ../frontend/rtre-webbapplication/
      - name: Build Frontend image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: frontend/app:latest
      - name: Get Bimserver from DockerHub and run
        run: |
          docker pull disitlab/bimserver:1.5.182
          docker run -p 8082:8080 disitlab/bimserver:1.5.182
      - name: Create Springboot container
        run: docker run -p 3030:3030 backend/app:latest
      - name: Create Frontend container
        run: docker run -p 8080:80 frontend/app:latest
      - name: Run cypress test
        run: |
          npm i
          npm run cy:run
