name: Server CI/CD

on:
  push:
    branches:
      - 'RTRE20-75-skapa-en-fungerande-chatt-system2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build Maven
        run: |
          cd server
          mvn install 
          mvn -B clean package 
          mvn spring-boot:run
