name: Workflow

on:
  push:
    branches:
      - 'RTRE20-75-skapa-en-fungerande-chatt-system2'


jobs:
  build:
     runs-on: ubuntu-latest
     steps:
        - name: Set up JDK 1.8
        - uses: actions/setup-java@1
          with:
            java-version: 1.8
        - name: Maven build
          uses: actions/checkout@v2
          run: |
            cd Server/
            chmod +x ./
            mvn -B clean package 
        - name: Maven run 
          run: |
            mvn spring-boot:run
